apiVersion: 1

contactPoints:
  - orgId: 1
    name: AlertManager
    receivers:
      - uid: alertmanager
        type: prometheus-alertmanager
        settings:
          url: http://alertmanager:9493
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: AlertManager
    group_by: ['alertname', 'grafana_folder', 'service']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
